name: Build App

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: npm install

    - name: Build the app
      run: npm run build
