name: Build App

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: npm install

    - name: Build the app
      run: npm run build
    - name: Trigger workflow on main branch
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.GH_TOKEN }}
        repository: ${{ github.repository }}
        event-type: trigger-workflow
        client-payload: '{"branch": "main"}'